# Project: Lab8
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o Usuario.o Post.o Comment.o
LINKOBJ  = main.o Usuario.o Post.o Comment.o
LIBS     = -L"C:/Users/Dell/Documents/progra_3/Dev-Cpp/MinGW64/lib" -L"C:/Users/Dell/Documents/progra_3/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Users/Dell/Documents/progra_3/Dev-Cpp/MinGW64/include" -I"C:/Users/Dell/Documents/progra_3/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/Dell/Documents/progra_3/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/Dell/Documents/progra_3/Dev-Cpp/MinGW64/include" -I"C:/Users/Dell/Documents/progra_3/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/Dell/Documents/progra_3/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/Dell/Documents/progra_3/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Lab8.exe
CXXFLAGS = $(CXXINCS) -std=c++11
CFLAGS   = $(INCS) -std=c++11
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

Usuario.o: Usuario.cpp
	$(CPP) -c Usuario.cpp -o Usuario.o $(CXXFLAGS)

Post.o: Post.cpp
	$(CPP) -c Post.cpp -o Post.o $(CXXFLAGS)

Comment.o: Comment.cpp
	$(CPP) -c Comment.cpp -o Comment.o $(CXXFLAGS)
